# Generated by Django 3.2.9 on 2021-11-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
